version: '3'

volumes:
  static:
  media:
  pg_data:

networks:
  kittygram-network:
    driver: bridge

services:
  gateway:
    image: alexeykuzko/kittygram_gateway:latest
    container_name: gateway
    ports:
      - '80:80/tcp'
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram-network
    volumes:
      - static:/var/html/backend
      - media:/var/html/media
      - static:/var/html/static

  backend:
    image: alexeykuzko/kittygram_backend:latest
    container_name: backend
    restart: always
    env_file: .env
    networks:
      - kittygram-network
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres
    
  frontend:
    image: alexeykuzko/kittygram_frontend:latest
    container_name: frontend
    restart: always
    networks:
      - kittygram-network
    volumes:
      - static:/app/build
    
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram-network

