name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Configure Yandex Cloud
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON }}

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: ./infra
        run: terraform plan
        env:
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_ssh_key_content: ${{ secrets.SSH_KEY }}
          TF_VAR_service_account_key_file: ${{ secrets.SA_KEY_FILE }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: ./infra
        run: terraform apply -auto-approve
        env:
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_ssh_key_content: ${{ secrets.SSH_KEY }}
          TF_VAR_service_account_key_file: ${{ secrets.SA_KEY_FILE }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: ./infra
        run: terraform destroy -auto-approve
        env:
          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_ssh_key_content: ${{ secrets.SSH_KEY }}
          TF_VAR_service_account_key_file: ${{ secrets.SA_KEY_FILE }}